apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-operator
  namespace: canary-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: ghcr.io/example/canary-operator:dev
          env:
            - name: PROMETHEUS_URL
              value: http://prometheus.monitoring.svc.cluster.local:9090

