apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-operator
  namespace: canary-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: ghcr.io/example/canary-operator:prod
          env:
            - name: PROMETHEUS_URL
              value: http://prometheus.monitoring.svc.cluster.local:9090
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

